# Generated by Django 4.2.2 on 2024-03-01 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WhoisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_name', models.CharField(max_length=255, unique=True)),
                ('registrar', models.TextField(blank=True)),
                ('registrant_name', models.CharField(blank=True, max_length=255)),
                ('registrant_organization', models.CharField(blank=True, max_length=255)),
                ('creation_date', models.DateTimeField(blank=True, null=True)),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
                ('expiration_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
