# Generated by Django 4.2.2 on 2024-03-02 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whoischeck', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WhoisResult',
        ),
    ]
