# Generated by Django 4.2.2 on 2024-03-02 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('whoischeck', '0002_delete_whoisresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhoisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('domain_name', models.CharField(help_text='Write without http or https. example: ebay.com, amazon.com, google.com.bd etc', max_length=255, unique=True)),
                ('registrar', models.TextField(blank=True)),
                ('registrant_name', models.CharField(blank=True, max_length=255)),
                ('registrant_organization', models.CharField(blank=True, max_length=255)),
                ('creation_date', models.DateTimeField(blank=True, null=True)),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
                ('expiration_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
