# Generated by Django 4.2.2 on 2024-03-02 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whoischeck', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='whoisresult',
            name='name_server',
            field=models.TextField(blank=True, null=True),
        ),
    ]
