# Generated by Django 4.2.2 on 2024-03-02 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whoischeck', '0004_whoisresult_name_server'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whoisresult',
            name='registrant_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
