# Generated by Django 4.2.2 on 2024-03-02 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whoischeck', '0005_alter_whoisresult_registrant_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whoisresult',
            name='registrar',
            field=models.TextField(blank=True, null=True),
        ),
    ]
