# Generated by Django 4.2.2 on 2024-03-02 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whoischeck', '0006_alter_whoisresult_registrar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whoisresult',
            name='registrant_organization',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
