# Generated by Django 4.2.2 on 2024-03-02 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whoischeck', '0007_alter_whoisresult_registrant_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whoisresult',
            name='domain_name',
            field=models.CharField(help_text='Write without http or https. example: ebay.com, amazon.com, google.com.bd etc', max_length=255),
        ),
    ]
