# Generated by Django 4.2.2 on 2023-11-07 00:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exsite',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='exsite',
            name='facebook_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exsite',
            name='instagram_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exsite',
            name='linkedin_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exsite',
            name='location',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exsite',
            name='mask_icon',
            field=models.FileField(blank=True, null=True, upload_to='site_image/', validators=[django.core.validators.FileExtensionValidator(['svg'])]),
        ),
        migrations.AlterField(
            model_name='exsite',
            name='og_image',
            field=models.ImageField(blank=True, null=True, upload_to='site_image/'),
        ),
        migrations.AlterField(
            model_name='exsite',
            name='phone',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='exsite',
            name='site_description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='exsite',
            name='site_favicon',
            field=models.ImageField(blank=True, null=True, upload_to='site_image/'),
        ),
        migrations.AlterField(
            model_name='exsite',
            name='site_logo',
            field=models.ImageField(blank=True, null=True, upload_to='site_image/'),
        ),
        migrations.AlterField(
            model_name='exsite',
            name='site_meta_tag',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='exsite',
            name='slogan',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='exsite',
            name='trademark',
            field=models.ImageField(blank=True, null=True, upload_to='site_image/'),
        ),
        migrations.AlterField(
            model_name='exsite',
            name='twitter_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
