# Generated by Django 4.2.2 on 2023-11-14 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='top_banenr',
        ),
        migrations.RemoveField(
            model_name='page',
            name='top_tagline',
        ),
    ]
