# Generated by Django 4.2.2 on 2023-11-16 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_blogcomments'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcomments',
            name='parent',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='child', to='cms.blogcomments'),
            preserve_default=False,
        ),
    ]
