# Generated by Django 4.2.2 on 2023-12-04 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_alter_blogcomments_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogcomments',
            options={'ordering': ['-created_at']},
        ),
    ]
