# Generated by Django 4.2.2 on 2023-11-18 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_activity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='type',
            new_name='ac_type',
        ),
    ]
