# Generated by Django 4.2.2 on 2024-01-02 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_activity_options_rename_type_activity_ac_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpertType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
    ]
