# Generated by Django 4.2.2 on 2024-01-04 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_expertiesprofile_expertprofileapprovalrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expertprofileapprovalrequest',
            old_name='notarised_doc',
            new_name='notarised_suporting_doc',
        ),
    ]
