# Generated by Django 4.2.2 on 2024-01-05 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_rename_notarised_doc_expertprofileapprovalrequest_notarised_suporting_doc'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExpertProfileApprovalRequest',
        ),
    ]
