# Generated by Django 4.2.2 on 2024-01-05 08:16

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_delete_expertprofileapprovalrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpertProfileApprovalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suporting_doc', models.FileField(upload_to='approval_request_files/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png'])])),
                ('suporting_url', models.URLField()),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expert_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expertise_profile_approval_request', to='accounts.expertiesprofile')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='experties_approvals', to='accounts.approvalstatus')),
            ],
        ),
    ]
