# Generated by Django 4.2.2 on 2024-01-05 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_expertprofileapprovalrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expertprofileapprovalrequest',
            old_name='remarks',
            new_name='office_remarks',
        ),
        migrations.AddField(
            model_name='expertprofileapprovalrequest',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
