# Generated by Django 4.2.2 on 2024-01-05 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_rename_remarks_expertprofileapprovalrequest_office_remarks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expertprofileapprovalrequest',
            name='suporting_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
