# Generated by Django 4.2.2 on 2024-01-05 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_alter_expertprofileapprovalrequest_suporting_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExpertProfileApprovalRequest',
        ),
    ]
