# Generated by Django 4.2.2 on 2024-01-07 11:46

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_expertprofileapprovalrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='verificationfiles',
            old_name='remarks',
            new_name='office_remarks',
        ),
        migrations.AlterField(
            model_name='approvalstatus',
            name='title',
            field=models.CharField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator(flags=re.RegexFlag['IGNORECASE'], message="Title must be 'approved', 'rejected', or 'pending', optionally followed by a hyphen and additional words.", regex='^(approved|rejected|pending|modified)(?:-[\\w-]*)?$')]),
        ),
    ]
