# Generated by Django 4.2.2 on 2024-01-09 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_alter_userverificationrequest_options_and_more'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='expertprofileapprovalrequest',
        #     name='status',
        #     field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='experties_approvals', to='accounts.approvalstatus'),
        # ),
    ]
