# Generated by Django 4.2.2 on 2024-01-09 00:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_alter_expertprofileapprovalrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expertiesprofile',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='expertprofileapprovalrequest',
            name='status',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='experties_approvals', to='accounts.approvalstatus'),
        ),
    ]
