# Generated by Django 4.2.2 on 2024-01-09 02:37

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_remove_expertprofileapprovalrequest_expert_profile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpertiesProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250)),
                ('experience_years', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expert_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_of_expert_type', to='accounts.experttype')),
                ('skills', models.ManyToManyField(related_name='expert_profile_of_skills', to='accounts.skill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expert_profiles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExpertProfileApprovalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_title', models.CharField(max_length=150)),
                ('suporting_doc', models.FileField(upload_to='approval_request_files/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png'])])),
                ('suporting_url', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('office_remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expert_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expertise_profile_approval_request', to='accounts.expertiesprofile')),
                ('status', models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='experties_approvals', to='accounts.approvalstatus')),
            ],
        ),
    ]
