# Generated by Django 4.2.2 on 2024-01-01 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0005_alter_weekendday_day_of_week'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offday',
            old_name='date',
            new_name='selected_date',
        ),
    ]
