# Generated by Django 4.2.2 on 2023-11-13 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_servicecategory_service_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecategory',
            name='banner',
            field=models.ImageField(default='', upload_to='service/category_banner'),
            preserve_default=False,
        ),
    ]
