# Generated by Django 4.2.2 on 2023-11-14 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_service_category_remove_service_categories_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='category',
        ),
    ]
