# Generated by Django 4.2.2 on 2023-12-04 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_alter_service_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderInvoice',
            fields=[
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='invoice', serialize=False, to='service.order')),
                ('filepath', models.FileField(upload_to='payment_instruction/')),
                ('validity', models.DateTimeField()),
                ('gateway', models.CharField(default='', max_length=50)),
                ('paid', models.BooleanField(default=False)),
                ('paid_on', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('invoice_initiatd', 'Invoice Initiatd'), ('processing', 'Processing'), ('confirm', 'Confirm'), ('payment_reject', 'Payment Reject'), ('payment_pending', 'Payment Pending'), ('shipped', 'Shipped'), ('completed', 'Completed'), ('canceled', 'Canceled')], db_index=True, default='pending', max_length=100),
        ),
    ]
