# Generated by Django 4.2.2 on 2023-12-05 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0010_orderitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
