# Generated by Django 4.2.2 on 2023-12-05 06:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shcurrency', '0001_initial'),
        ('service', '0011_delete_orderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trxID', models.TextField()),
                ('status', models.CharField(blank=True, choices=[('authorized', 'Authorized'), ('captured', 'Captured'), ('refunded', 'Refunded'), ('failed', 'Failed')], db_index=True, max_length=100, null=True)),
                ('gateway', models.CharField(blank=True, max_length=20, null=True)),
                ('amount', models.FloatField(default=0)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_trans', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_trans', to='service.order')),
                ('paymemt_currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trans_currency', to='shcurrency.currency')),
            ],
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
