# Generated by Django 4.2.2 on 2023-12-20 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0012_ordertransaction_delete_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='price',
        ),
        migrations.AddField(
            model_name='order',
            name='amount',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
