# Generated by Django 4.2.2 on 2023-12-20 00:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0013_remove_order_price_order_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordertransaction',
            name='check_and_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ordertransaction',
            name='check_and_reject',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ordertransaction',
            name='mobile',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ordertransaction',
            name='screenshoot',
            field=models.FileField(default='', upload_to='transactions/screenshoot', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'pdf'], message='Only image (jpg, jpeg, png, gif) and PDF files are allowed.')]),
            preserve_default=False,
        ),
    ]
