# Generated by Django 4.2.2 on 2023-12-25 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0016_order_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderinvoice',
            name='paid',
        ),
        migrations.RemoveField(
            model_name='orderinvoice',
            name='paid_on',
        ),
        migrations.AddField(
            model_name='orderinvoice',
            name='due',
            field=models.BooleanField(default=True),
        ),
    ]
