# Generated by Django 4.2.2 on 2023-12-25 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0017_remove_orderinvoice_paid_remove_orderinvoice_paid_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinvoice',
            name='validity',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
