# Generated by Django 4.2.2 on 2023-12-25 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0018_alter_orderinvoice_validity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinvoice',
            name='validity',
            field=models.DateTimeField(),
        ),
    ]
