# Generated by Django 4.2.2 on 2023-12-30 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0019_alter_orderinvoice_validity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('invoice_initiatd', 'Invoice Initiatd'), ('processing', 'Processing'), ('confirm', 'Confirm'), ('payment_reject', 'Payment Reject'), ('payment_pending', 'Payment Pending'), ('shipped', 'Shipped'), ('completed', 'Completed'), ('canceled', 'Canceled'), ('abandoned', 'Abandoned')], db_index=True, default='pending', max_length=100),
        ),
        migrations.CreateModel(
            name='ProjectTodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.TextField()),
                ('sort_order', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_todo', to='service.project')),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordertext_project_todo', to='service.ordertext')),
            ],
        ),
    ]
