# Generated by Django 4.2.2 on 2023-12-30 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0020_alter_order_status_projecttodo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projecttodo',
            old_name='step',
            new_name='milestone',
        ),
        # migrations.AddField(
        #     model_name='projecttodo',
        #     name='m_type',
        #     field=models.CharField(blank=True, choices=[('backend', 'Backend'), ('frontend', 'Front End'), ('design', 'Design'), ('copywriting', 'Compy Writing')], db_index=True, max_length=100, null=True),
        # ),
    ]
