# Generated by Django 4.2.2 on 2023-12-30 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0021_rename_step_projecttodo_milestone_projecttodo_m_type'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='projecttodo',
        #     name='m_type',
        #     field=models.CharField(blank=True, choices=[('backend', 'Backend'), ('frontend', 'Front End'), ('design', 'Design'), ('copywriting', 'Copy Writing')], db_index=True, max_length=100, null=True),
        # ),
    ]
