# Generated by Django 4.2.2 on 2023-12-30 20:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('service', '0022_alter_projecttodo_m_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttodo',
            name='required_days',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='projectcontributor',
            name='contributor',
        ),
        migrations.AddField(
            model_name='projectcontributor',
            name='contributor',
            field=models.ManyToManyField(related_name='contributor', to=settings.AUTH_USER_MODEL),
        ),
    ]
