# Generated by Django 4.2.2 on 2023-12-30 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0023_projecttodo_required_days_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectcontributor',
            name='contributor',
        ),
    ]
