# Generated by Django 4.2.2 on 2023-12-31 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0024_remove_projectcontributor_contributor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projecttodo',
            options={'ordering': ('sort_order',)},
        ),
    ]
