# Generated by Django 4.2.2 on 2023-12-31 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0025_alter_projecttodo_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttodo',
            name='target_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
