# Generated by Django 4.2.2 on 2023-12-31 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0026_projecttodo_target_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttodo',
            name='target_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
