# Generated by Django 4.2.2 on 2024-01-01 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0027_alter_projecttodo_target_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttodo',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projecttodo',
            name='milestone',
            field=models.TextField(max_length=300),
        ),
    ]
