# Generated by Django 4.2.2 on 2024-01-02 08:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('service', '0028_projecttodo_description_alter_projecttodo_milestone'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcontributor',
            name='contributor',
            field=models.ManyToManyField(related_name='user_contributing_to', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Interactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributor_interactions', to='service.projectcontributor')),
                ('todo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todo_interactions', to='service.projecttodo')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
    ]
