# Generated by Django 4.2.2 on 2024-01-02 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0029_projectcontributor_contributor_interactions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectcontributor',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_contributors', to='service.project'),
        ),
    ]
