# Generated by Django 4.2.2 on 2024-01-02 08:55

from django.db import migrations
import service.helpers


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0030_alter_projectcontributor_project'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='projectcontributor',
        #     name='m_type',
        #     field=service.helpers.MultiSelectField(db_index=True, default='backend', max_length=100),
        # ),
    ]
