# Generated by Django 4.2.2 on 2024-01-02 09:30

from django.db import migrations
# import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0034_alter_projectcontributor_m_type'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='projectcontributor',
        #     name='m_type',
        #     field=multiselectfield.db.fields.MultiSelectField(choices=[('backend', 'Backend'), ('frontend', 'Front End'), ('design', 'Design'), ('copywriting', 'Copy Writing')], default='backend', max_length=100),
        # ),
    ]
