# Generated by Django 4.2.2 on 2024-01-02 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0035_projectcontributor_m_type'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='projectcontributor',
        #     name='m_type',
        # ),
    ]
