# Generated by Django 4.2.2 on 2024-01-02 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0038_projectcontributor_expert_field'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='projectcontributor',
        #     name='expert_field',
        # ),
    ]
