# Generated by Django 4.2.2 on 2024-01-02 09:43

from django.db import migrations
# import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0040_projectcontributor_for_task_of'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='projectcontributor',
        #     name='for_task_of',
        #     field=multiselectfield.db.fields.MultiSelectField(choices=[('backend', 'Backend'), ('frontend', 'Front End'), ('design', 'Design'), ('copywriting', 'Copy Writing')], max_length=100),
        # ),
    ]
