# Generated by Django 4.2.2 on 2024-01-02 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0042_remove_projectcontributor_for_task_of_and_more'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='projectcontributor',
        #     name='for_task_of',
        # ),
    ]
