# Generated by Django 4.2.2 on 2024-01-02 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_experttype'),
        ('service', '0044_projectcontributor_for_task_of_and_more'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='projecttodo',
        #     name='m_type',
        #     field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.experttype'),
        # ),
    ]
