# Generated by Django 4.2.2 on 2024-01-02 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0048_alter_projecttodo_m_type'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='projecttodo',
        #     name='m_type',
        # ),
    ]
