# Generated by Django 4.2.2 on 2024-01-02 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_experttype'),
        ('service', '0050_remove_projecttodo_m_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttodo',
            name='miltstone_type',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.experttype'),
        ),
    ]
