# Generated by Django 4.2.2 on 2024-01-02 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_experttype'),
        ('service', '0051_projecttodo_miltstone_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttodo',
            name='miltstone_type',
            field=models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='accounts.experttype'),
        ),
    ]
