# Generated by Django 4.2.2 on 2024-01-09 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_alter_expertprofileapprovalrequest_status'),
        ('service', '0052_alter_projecttodo_miltstone_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectcontributor',
            name='contributor',
            field=models.ManyToManyField(related_name='contributing_to', to='accounts.expertiesprofile'),
        ),
    ]
