# Generated by Django 4.2.2 on 2024-01-09 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_alter_expertiesprofile_id_and_more'),
        ('service', '0054_alter_projectcontributor_contributor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectcontributor',
            name='contributor',
            field=models.ManyToManyField(related_name='contributing_to', to='accounts.expertiesprofile'),
        ),
    ]
