# Generated by Django 4.2.2 on 2024-01-09 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_alter_expertiesprofile_id_and_more'),
        ('service', '0056_remove_projectcontributor_contributor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectContributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contributor', models.ManyToManyField(related_name='contributing_to', to='accounts.expertiesprofile')),
                ('for_task_of', models.ManyToManyField(related_name='contributors_of_expertise', to='accounts.experttype')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_contributors', to='service.project')),
            ],
        ),
        migrations.CreateModel(
            name='Interactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributor_interactions', to='service.projectcontributor')),
                ('todo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todo_interactions', to='service.projecttodo')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
    ]
