# Generated by Django 4.2.2 on 2024-01-09 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0057_projectcontributor_interactions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectcontributor',
            name='contributor',
        ),
    ]
