# Generated by Django 4.2.2 on 2024-01-09 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_expertiesprofile_expertprofileapprovalrequest'),
        ('service', '0058_remove_projectcontributor_contributor'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcontributor',
            name='contributor',
            field=models.ManyToManyField(related_name='contributing_to', to='accounts.expertiesprofile'),
        ),
    ]
