# Generated by Django 4.2.2 on 2024-01-09 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_expertiesprofile_expertprofileapprovalrequest'),
        ('service', '0060_alter_projectcontributor_contributor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectcontributor',
            name='contributor',
            field=models.ManyToManyField(limit_choices_to={'expertise_profile_approval_request__status__title__iexact': 'approved'}, related_name='contributing_to', to='accounts.expertiesprofile'),
        ),
    ]
