# Generated by Django 4.2.2 on 2024-01-09 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0063_projectcontributor_interactions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectcontributor',
            name='contributor',
        ),
        migrations.RemoveField(
            model_name='projectcontributor',
            name='for_task_of',
        ),
        migrations.RemoveField(
            model_name='projectcontributor',
            name='project',
        ),
        migrations.DeleteModel(
            name='Interactions',
        ),
        migrations.DeleteModel(
            name='ProjectContributor',
        ),
    ]
