# Generated by Django 4.2.2 on 2024-01-09 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0065_projectcontributor_interactions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectcontributor',
            old_name='for_task_of',
            new_name='task_type',
        ),
    ]
