# Generated by Django 4.2.2 on 2024-01-10 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_expertiesprofile_expertprofileapprovalrequest'),
        ('service', '0066_rename_for_task_of_projectcontributor_task_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttodo',
            name='miltstone_type',
            field=models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, related_name='type_todos', to='accounts.experttype'),
        ),
    ]
