# Generated by Django 4.2.2 on 2024-01-10 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0067_alter_projecttodo_miltstone_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='interactions',
            name='ans_required',
            field=models.BooleanField(default=True),
        ),
    ]
