# Generated by Django 4.2.2 on 2024-01-10 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0068_interactions_ans_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interactions',
            name='ans_required',
            field=models.BooleanField(default=True, verbose_name='Answer Required'),
        ),
    ]
