# Generated by Django 4.2.2 on 2024-01-10 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0069_alter_interactions_ans_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='interactions',
            name='waited_for_answer',
            field=models.IntegerField(default=0),
        ),
    ]
