# Generated by Django 4.2.2 on 2024-01-10 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0070_interactions_waited_for_answer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interactions',
            old_name='waited_for_answer',
            new_name='waited_for_reply',
        ),
    ]
