# Generated by Django 4.2.2 on 2024-01-10 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0071_rename_waited_for_answer_interactions_waited_for_reply'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Interactions',
        ),
    ]
