# Generated by Django 4.2.2 on 2024-01-10 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0073_interactions'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Interactions',
        ),
    ]
