

from . import BASE_DIR, env

DEFAULT_FROM_EMAIL = env("SH_DEFAULT_FROM_EMAIL")
EMAIL_HOST = env("SH_EMAIL_HOST")
EMAIL_PORT= env("SH_EMAIL_PORT")
EMAIL_HOST_USER = env("SH_EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = env("SH_EMAIL_HOST_PASSWORD")
EMAIL_USE_TLS=False
EMAIL_USE_SSL=True

